let products = [

          {
            id: 201,
            title: "Harry Potter and the Order of the Phoenix",
            author: "J.K.Rowling",
            genre: "Fantasy",
            price: 57,
            image: "images/book1.jpeg",
            AvailableInventory: 7,
          },
          {
            id: 202,
            title: "A Long Petal of the Sea",
            author: "Isabel Allende",
            genre: "Historical",
            price: 66,
            image: "images/book2.jpg",
            AvailableInventory: 6,
          },
          {
            id: 203,
            title: "Dear Edward: A Read with Jenna Pick",
            author: "Ann Napolitano",
            genre: "Fiction",
            price: 51,
            image: "images/book3.jpg",
            AvailableInventory: 8,
          },
          {
            id: 204,
            title: "To Kill a Mockingbird",
            author: "Harper Lee",
            genre: "Fiction",
            price: 55,
            image: "images/book4.jpg",
            AvailableInventory: 5,
          },
          {
            id: 205,
            title: "Atomic Habits",
            author: "James Clear",
            genre: "Self help",
            price: 66,
            image: "images/book5.jpg",
            AvailableInventory: 10,
          },
          {
            id: 206,
            title: "The Alchemist",
            author: "Paulo Coelho",
            genre: "Philosophical",
            price: 53,
            image: "images/book6.jpg",
            AvailableInventory: 10,
          },
          {
            id: 207,
            title: "Famous Five: Five Go Off to Camp",
            author: "Guid Blyton",
            genre: "Adventure",
            price: 34,
            image: "images/book7.jpg",
            AvailableInventory: 8,
          },
          {
            id: 208,
            title: "Little Women",
            author: "Louisa May Alcott",
            genre: "Classic",
            price: 65,
            image: "images/book8.jpg",
            AvailableInventory: 9,
          },
          {
            id: 209,
            title: "Middlemarch",
            author: "George Eliot",
            genre: "Commentary",
            price: 95,
            image: "images/book9.jpg",
            AvailableInventory: 6,
          },
          {
            id: 210,
            title: "Mrs Dalloway",
            author: "Virginia Woolf",
            genre: "Literature",
            price: 55,
            image: "images/book10.jpg",
            AvailableInventory: 9,
          },
          {
            id: 211,
            title: "Continental Drift",
            author: " Russell Banks",
            genre: "Political ",
            price: 56,
            image: "images/book11.jpg",
            AvailableInventory: 8,
          },
          {
            id: 212,
            title: "The Little Prince",
            author: "Antoine de Saint-Exupéry",
            genre: "Adventure",
            price: 62,
            image: "images/book12.jpg",
            AvailableInventory: 10,
          }
]